$download_mysql = <<-SCRIPT
    apt update && \
    apt install mysql-server-5.7 -y && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.define "mysqldb" do |mysql|
        mysql.vm.network "public_network", ip: "192.168.0.25"
        mysql.vm.synced_folder "./configs", "/configs"
        
        mysql.vm.provision "shell",
            inline: "cat /configs/ssh-key_bionic >> .ssh/authorized_keys"
        mysql.vm.provision "shell",
            inline: $download_mysql
        mysql.vm.provision "shell",
            inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
        mysql.vm.provision "shell",
            inline: "systemctl restart mysql"
        mysql.vm.synced_folder ".", "/vagrant", disabled: true
    end

    config.vm.define "phpweb" do |phpweb|
        phpweb.vm.network "forwarded_port", guest: 8888, host:8080
        phpweb.vm.network "public_network", ip: "192.168.0.26"

        phpweb.vm.provision "shell",
            inline: "sudo apt update && sudo apt install puppet -y"
        phpweb.vm.provision "puppet" do |puppet|
            puppet.manifests_path = "./configs/manifests"
            puppet.manifest_file = "phpweb.pp"
        end
    end 

    config.vm.define "mysqlserver" do |mysqlserver|
        mysqlserver.vm.network "public_network", ip: "192.168.0.24"
        mysqlserver.vm.provision "shell",
            inline: "cat /vagrant/configs/ssh-key_bionic >> .ssh/authorized_keys"
    end

    config.vm.define "ansible" do |ansible|
        ansible.vm.network "public_network", ip: "192.168.0.23"
        
        ansible.vm.provision "shell",
        inline: "cp /vagrant/ssh-key_bionic_priv /home/vagrant && \
                chmod 600 /home/vagrant/ssh-key_bionic_priv && \
                sudo chown vagrant:vagrant ssh-key_bionic_priv && \
                cp /vagrant/configs/ssh-key_bionic /home/vagrant && \
                sudo chown vagrant:vagrant ssh-key_bionic"
        
        ansible.vm.provision "shell",
            inline: "apt-get update && \
                     apt-get install -y software-properties-common && \
                     apt-add-repository --yes --update ppa:ansible/ansible && \
                     apt-get install -y ansible"
    end
end