$download_mysql = <<-SCRIPT
    apt update && \
    apt install mysql-server-5.7 -y && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 80, host:8080
    config.vm.network "public_network", ip: "192.168.0.25"
    config.vm.synced_folder "./configs", "/configs"
    
    config.vm.provision "shell",
        inline: "cat /configs/ssh-key_bionic >> .ssh/authorized_keys"
    config.vm.provision "shell",
        inline: $download_mysql
    config.vm.provision "shell",
        inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    config.vm.provision "shell",
        inline: "systemctl restart mysql"
    config.vm.synced_folder ".", "/vagrant", disabled: true
end