---
- hosts: mysql
  handlers:
    - name: "Restart MySQL"
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: "Install the packages | MySQL"
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: latest
      become: yes
      with_items: 
          - mysql-server-5.6
          - python-mysqldb

    - name: "Create MySQL"
      mysql_db: 
        name: wordpress_db
        login_user: root
        state: present
    
    - name: "Create the user for MySQL"
      mysql_user:
        login_user: root
        name: wordpress_user
        password: exemplo123
        priv: 'wordpress_db.*:ALL'
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        -  '127.0.0.1'
        - '192.168.0.31'

    - name: "Configure MySQL to accept remote connections"
      copy:
        src: 'files/my.cnf'
        dest: '/etc/mysql/my.cnf'
      become: yes
      notify:
        - Restart MySQL

- hosts: wordpress
  handlers:
    - name: "Restart Apache"
      service:
        name: apache2
        state: restarted
      become: yes 

  tasks:
    - name: "Install the packages | Wordpress"
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: latest
      become: yes
      with_items: 
          - php5
          - apache2
          - libapache2-mod-php5
          - php5-gd
          - libssh2-php
          - php5-mcrypt
          - php5-mysql

    - name: "Download Wordpress file"
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: "Unzips the Wordpress file"
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: yes

    - name: "Copy Wordpress configuration file"
      copy: 
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: "Configure wp-config with Database entries"
      replace: 
        path: '/var/www/wordpress/wp-config.php'
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: 'exemplo123'}
        - { regex: 'localhost', value: '192.168.0.31'}
      become: yes

    - name: "Configure Apache to serve Wordpress"
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify: 
        - Restart Apache