Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "ubuntu_wordpress"
    end  

    config.vm.define "wordpress" do |wordpress|
        wordpress.vm.network "public_network", ip: "192.168.0.30"
  
        wordpress.vm.provision "shell",
          inline: "cat /vagrant/.ssh-key_priv >> .ssh/authorized_keys && \
                   cat /vagrant/configs/.ssh-key_pub >> .ssh/authorized_keys"
    end
end